export const statsObject = {
  bb: 'BB means base on balls, but you probably know it as WALKS. This stat counts the number of times the batter gets 4 balls (non-strikes) in a single at-bat, and is awarded first base.',
  rbi: 'RBI means RUNS BATTED IN. This is one of the more important stats to look at. This counts the number of runs the batter brings in to the team from an at-bat. If a batter hits a home run with a runner on first, that counts as 2 RBI (the runner on first scores, as well as the batter).',
  sb: 'SB means STOLEN BASE. To steal a base, a runner must make it to the next base without the batter hitting the ball, and reach that base safely.',
  hr: 'HR means HOME RUN. Probably the most popular stat in baseball. This simply means the batter hits the ball over the fence (inside the field of play of course..)!',
  obp: 'OBP means ON BASE PERCENTAGE. This is more on the advanced side of baseball statistics, but still good to konw. This is the percentage of times a batter reaches base safely, either by hitting the ball, being walked by the pitcher, or getting hit by the pitch (OUCH!).',
  r: 'R simply means RUNS. This counts the number of times a player reaches home plate safely and scores a run for his team.',
  ab: 'AB means AT BAT. It\'s mostly straight forward, meaning this counts the number of times a player has come up to the plate to attempt to hit the ball. Interestingly enough, there are several scenarios in which a player\s appearance at the plate doesn\'t actually count toward the AT BAT... weird. ',
  avg: 'AVG means AVERAGE (or BATTING AVERAGE). Another household stat, this number represents the amount of times a batter hits the ball and reaches base safely out of 1000 at-bats. An AVG of .300 means out of every 1000 at bats, the hitter gets 300 hits. This average is considered very good! Baseball is the only sport where failing 7/10 times is considered great! (Think about it...)',
  slg: 'SLG means SLUGGING PERCENTAGE. Another of the more advanced stats, SLUGGING is a long, crazy formula that attempts to put into numbers the amount of bases a player gains per hit. For example, a Home Run gains 4 bases, a triple 3 bases, double 2 bases, and a single 1 base. SLG meshes all the hits togther and spits out a total bases per hit number. WEIRD! ',
  ops: 'OPS means ON BASE PLUS SLUGGING. Exactly what it sounds like, it adds a players OBP and SLG. If a player has a OBP of .400, and a SLG of .400, their SLG is .800. The average for SLG is usually around .700. Great players can have SLG over 1.000!',
  so: 'SO means STRIKE OUT. Besides Home Run, probably the most commonly known baseball stat. This is one you DON\'T want to have many of. When a batter gets 3 strikes in a single at bat, the batter is OUT, and heads back to the bench. Nobody wants to strike out...'
}
